In [1]:
from langchain.schema.runnable import RunnablePassthrough
from langchain_core.prompts import PromptTemplate
from langchain_core.retrievers import BaseRetriever
from langchain_core.documents import Document
from langchain_google_genai import ChatGoogleGenerativeAI
import dotenv
dotenv.load_dotenv()

True

### PromptTemplate 에 기사내용

In [ ]:
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")

prompt = PromptTemplate.from_template("""
다음의 context를 읽고, 질문에 답해줘.
context: {context}
질문: {question}
""")

chain = prompt | llm

response = chain.invoke({
    'context': '''
다음 기사를 근거로 질문에 답하세요.
-----
제21대 대한민국 대통령에 이재명 더불어민주당 후보가 당선됐다.

초유의 비상계엄 사태와 윤석열 전 대통령 파면 속에 치러진 조기 대선에서 민심이 정권 교체를 선택한 것이다. 전국 최종 투표율은 79.4%를 기록, 총 3524만416명이 투표에 참여했다.

중앙선거관리위원회에 따르면 4일 오전 5시 10분 개표율 100%를 기준으로 기호 1번 더불어민주당 이재명 후보가 1728만7513표로 전체 49.42%를 득표했다. 1439만5639표를 얻은 기호 2번 국민의힘 김문수 후보(41.15%)를 8.27%p차로 앞서며 당선을 확정 지었다.

앞서 방송 3사(KBS·MBC·SBS) 출구조사에서는 이재명 후보가 51.7%를 득표해 과반을 넘길 것이라 예측됐지만, 최종적으로 과반을 하지는 못했다.

이재명 후보는 제21대 대통령 당선이 확실시된 4일 오전 서울 여의도 국회 앞에 마련된 야외무대에 "민주공화국 대한민국 시민 여러분께 진심으로 감사드린다"며 "여러분들이 제게 기대하시고 맡긴 그 사명을 한순간도 잊지 않고 한 치의 어긋남도 없이 반드시, 확실히 이행하겠다"고 말했다.
-----''',
    'question': "한국의 대통령은?"
})
print(response.content)

이재명

### Hub에서 pull 한 prompt에 기사내용

In [5]:
from langchain import hub
prompt = hub.pull('rlm/rag-prompt')
print(prompt)

chain = prompt | llm

response = chain.invoke({
    'context': '''다음 기사를 근거로 질문에 답하세요.
-----
제21대 대한민국 대통령에 이재명 더불어민주당 후보가 당선됐다.
초유의 비상계엄 사태와 윤석열 전 대통령 파면 속에 치러진 조기 대선에서 민심이 정권 교체를 선택한 것이다. 전국 최종 투표율은 79.4%를 기록, 총 3524만416명이 투표에 참여했다.
중앙선거관리위원회에 따르면 4일 오전 5시 10분 개표율 100%를 기준으로 기호 1번 더불어민주당 이재명 후보가 1728만7513표로 전체 49.42%를 득표했다. 1439만5639표를 얻은 기호 2번 국민의힘 김문수 후보(41.15%)를 8.27%p차로 앞서며 당선을 확정 지었다.
앞서 방송 3사(KBS·MBC·SBS) 출구조사에서는 이재명 후보가 51.7%를 득표해 과반을 넘길 것이라 예측됐지만, 최종적으로 과반을 하지는 못했다.
이재명 후보는 제21대 대통령 당선이 확실시된 4일 오전 서울 여의도 국회 앞에 마련된 야외무대에 "민주공화국 대한민국 시민 여러분께 진심으로 감사드린다"며 "여러분들이 제게 기대하시고 맡긴 그 사명을 한순간도 잊지 않고 한 치의 어긋남도 없이 반드시, 확실히 이행하겠다"고 말했다.
-----''',
    'question': '한국의 대통령은?'
})
print(response.content)

input_variables=['context', 'question'] input_types={} partial_variables={} metadata={'lc_hub_owner': 'rlm', 'lc_hub_repo': 'rag-prompt', 'lc_hub_commit_hash': '50442af133e61576e74536c6556cefe1fac147cad032f4377b60c436e6cdcb6e'} messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], input_types={}, partial_variables={}, template="You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.\nQuestion: {question} \nContext: {context} \nAnswer:"), additional_kwargs={})]
기사에 따르면 대한민국의 제21대 대통령은 이재명 더불어민주당 후보입니다. 그는 49.42%의 득표율로 당선되었습니다. 그는 민심이 정권 교체를 선택한 조기 대선에서 당선되었습니다.

### Simple Retriever 이용

In [ ]:
class SimpleRetriever(BaseRetriever):
    docs: list[Document]
    k: int = 5

    def _get_relevant_documents(self, query: str) -> list[Document]:
        return self.docs[:self.k]


document = Document(
    page_content='2025년 6월 3일에 당선된 제 21대 대통령은 더불어민주당 이재명이다.',
    metadata={'source': 'https://example.com'}
)

llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")

prompt = PromptTemplate.from_template("""
다음의 context를 읽고, 질문에 답해줘.
context: {context}
질문: {question}
""")

retriever = SimpleRetriever(docs=[document], k=1)
context = retriever.invoke('한국의 대통령은?')
# print(context)

chain = prompt | llm

response = chain.invoke({
    'question': '한국의 대통령은?',
    'context': retriever.invoke('한국의 대통령은?')
})
# print(response.content)

chain = {
    'context': retriever,
    'question': RunnablePassthrough()
} | prompt | llm
response = chain.invoke('한국의 대통령은?')
print(response.content)

한국의 대통령은 더불어민주당 이재명입니다.

### Wikipedia Retriever

In [10]:
from langchain.schema.runnable import RunnablePassthrough
from langchain_community.retrievers import WikipediaRetriever
retriever = WikipediaRetriever()

chain = {
    'context': retriever,
    'question': RunnablePassthrough()
} | prompt | llm

context = retriever.invoke('한국의 대통령은?')
print(context)

response = chain.invoke('한국의 대통령은?')
print(response.content)

[Document(metadata={'title': 'Democratic Party (South Korea, 2015)', 'summary': "The Democratic Party of Korea (DPK or DP; Korean: 더불어민주당, lit.\u2009'Together Democratic Party') is a liberal political party in South Korea. The DPK and its rival, the People Power Party (PPP), form the two major political parties of South Korea. It is the ruling party following the victory of Lee Jae Myung at the 2025 presidential election, and has been the largest party in the National Assembly since 2016, controlling a majority since 2020. It was previously the ruling party under Moon Jae-in from 2017 to 2022.\nThe Democratic Party was founded as the New Politics Alliance for Democracy (NPAD; 새정치민주연합) on 26 March 2014 as a merger between the previous Democratic Party and the preparatory committee of the New Political Vision Party (NPVP) led by Ahn Cheol-soo. The party changed its name to the current name on 28 December 2015. In 2022, the Democratic Party, the Open Democratic Party, and New Wave merged to form a big tent party.", 'source': 'https://en.wikipedia.org/wiki/Democratic_Party_(South_Korea,_2015)'}, page_content='The Democratic Party of Korea (DPK or DP; Korean: 더불어민주당, lit.\u2009\'Together Democratic Party\') is a liberal political party in South Korea. The DPK and its rival, the People Power Party (PPP), form the two major political parties of South Korea. It is the ruling party following the victory of Lee Jae Myung at the 2025 presidential election, and has been the largest party in the National Assembly since 2016, controlling a majority since 2020. It was previously the ruling party under Moon Jae-in from 2017 to 2022.\nThe Democratic Party was founded as the New Politics Alliance for Democracy (NPAD; 새정치민주연합) on 26 March 2014 as a merger between the previous Democratic Party and the preparatory committee of the New Political Vision Party (NPVP) led by Ahn Cheol-soo. The party changed its name to the current name on 28 December 2015. In 2022, the Democratic Party, the Open Democratic Party, and New Wave merged to form a big tent party.\n\n\n== History ==\n\n\n=== Formation and Ahn–Kim leadership (March – July 2014) ===\n\nOn 26 March 2014, the New Politics Alliance for Democracy was founded after an independent group led by Ahn Cheol-soo, in the process of forming the New Political Vision Party, merged with the Democratic Party led by Kim Han-gil. As a result, the former Democratic Party was absorbed into the NPAD and the preparatory committee of the NPVP was dissolved. Ahn and Kim jointly assumed leadership of the party as co-leaders. When the party performed poorly in by-elections that July, both leaders stepped down. The leadership of the party was then assumed by an emergency committee.\n\n\n=== Ahn–Moon split (2015–16) ===\nOn 7 February 2015, a party convention elected Moon Jae-in as the new leader of the party. Moon, who had previously served as chief of staff for former president Roh Moo-hyun, was the leader of the party\'s "pro-Roh" faction, opposed to Ahn and Kim. Moon came under fire for imposing a "pro-Roh hegemony" in the party, as Ahn and Kim were jeered and harassed at a memorial service for Roh held in May 2015.\nAs the factional conflict intensified, the party lost support, falling from around 40 to 30 percent in opinion polls. A survey conducted on 12–14 November 2015, showed that supporters of the party wanted Ahn and Seoul mayor Park Won-soon to assume the leadership alongside Moon. On 29 November, Ahn rejected a proposal from Moon to establish joint leadership and presented Moon with a demand to call a convention to elect a new party leader. Moon rejected his demand, and Ahn left the party.\nAhn was followed by a number of NPAD assembly members, including his former co-leader Kim Han-gil and Kwon Rho-kap, a former aide of President Kim Dae-jung from the party\'s stronghold of Honam. Ahn and Kim merged their groups with that of another defector from the NPAD, Chun Jung-bae, to form the People Party.\nFollowing the defections, the NPAD was renamed the Democratic Party on 28 December 2015, and Moon resigned as party leader on 27 January 2016. Subsequently, Kim Chong-in, an academic and former assemblyman who served as an economic advisor to President Park Geun-hye, was appointed party leader. Kim was viewed as an unexpected choice, as he had previously worked for the conservative Chun Doo-hwan and Roh Tae-woo administrations in the 1980s, serving as an assembly member for the ruling Democratic Justice Party and as health and welfare minister.\n\n\n=== Under Kim Chong-in (January–August 2016) ===\nKim Chong-in viewed the pro–Roh Moo-hyun faction and what he considered the extremist wing of the party as responsible for the party\'s troubles and pledged to diminish their influence.\nIn the lead-up to the 2016 legislative election, he deselected Lee Hae-chan, who had been Prime Minister under Roh and was now chairman of the Roh Moo-hyun Foundation, as a candidate. Lee left the party in response. Many of Kim\'s nominations for the party\'s list were rejected by the rest of the party leadership, while favored candidates of Moon were ranked near the t'), Document(metadata={'title': 'Gong Byeong-ho', 'summary': 'Gong Byeong-ho (Korean: 공병호, born May 10, 1960) is a South Korean economist and author. He is the founder of the Center for Free Enterprise, a libertarian think tank, and is the author of books on economics and management.\nSince 2020, Gong has promoted right-wing conspiracy theories about electoral fraud by the Democratic Party of Korea, for which he has been charged with spreading misinformation by the Seoul Election Commission.\n\n', 'source': 'https://en.wikipedia.org/wiki/Gong_Byeong-ho'}, page_content='Gong Byeong-ho (Korean: 공병호, born May 10, 1960) is a South Korean economist and author. He is the founder of the Center for Free Enterprise, a libertarian think tank, and is the author of books on economics and management.\nSince 2020, Gong has promoted right-wing conspiracy theories about electoral fraud by the Democratic Party of Korea, for which he has been charged with spreading misinformation by the Seoul Election Commission.\n\n\n== Early life and education ==\nGong, born in Chungmu (now Tongyeong), South Gyeongsang Province, South Korea, was the youngest of seven siblings. Having first left home to attend a high school in Busan, Gong eventually earned a degree in economics from Korea University in 1979, and completed a PhD in economics at Rice University in 1987.\n\n\n== Career ==\n\n\n=== Center for Free Enterprise ===\nGong joined the Korea Economic Research Institute (KERI) as a researcher in 1990, where he and a fellow researcher, Kim Chung-ho, began to develop ideas on the market economy. They criticized increasing business and banking restrictions on chaebols (South Korean conglomerates like Samsung and LG) that were popular at the time, advocating for less government regulation. Critics, in turn, accused KERI of being a puppet of the chaebols, as it was funded by the Federation of Korean Industries (FKI), a lobby group representing the same companies.\nGong founded the Center for Free Enterprise in 1997, as part of KERI, to promote libertarianism and free market economic principles. It was later spun off into a separate organization with the assistance of Sohn Byung-doo, the then-president of FKI.\nThe center has reprinted publications on libertarianism for Korean readers, including works by Friedrich Hayek, Ludwig von Mises, and Ayn Rand, and published books on libertarian policy proposals by Korean scholars. Gong was the center\'s director until 1999, departing to lead Internet start-up Intizen.\n\n\n=== Gong Institute ===\nIn 2001, Gong established the eponymous Gong Byeong-ho Research Institute, a self-run business and management consulting service. As of 2009, he had published more than 80 books and was giving almost 300 lectures a year on self-help and entrepreneurship.\n\n\n=== Politics ===\nGong briefly chaired the nomination committee of the Future Korea Party (FKP), which existed from February to May 2020. As it was composed of former members of the right-wing United Future Party (UFP), the UFP was accused by other parties of exploiting a loophole in a recently passed act to maximize allocated seats in the National Assembly; it merged into the UFP following the election.\nA minor scandal ensued when Gong announced the list of nominees, which placed the UFP\'s recommendations at the bottom, beneath FKP-chosen candidates that included a piano player and YouTuber. He apologized a few days later, and was replaced by Baekseok University professor Bae Gyu-han.\n\n\n== Election fraud claims ==\nGong established a YouTube channel in 2015 called "Gong Byeong-ho TV", and has since become a popular far-right social media influencer in South Korea. Videos on his channel cover topics such as the economy and politics, and in some cases have been flagged as violations of YouTube\'s content policies, including one on COVID-19 and another on election fraud.\n\n\n=== 2020 ===\nIn 2020, he claimed the vote in that year\'s legislative election had been manipulated after the Democratic Party of Korea won in a landslide, despite previous expectations that it would struggle. In a press release, Gong cited as evidence a report by University of Michigan professor Walter Mebane that found statistical anomalies in early voting.\nThe JoongAng and E-Korea said that Mebane lacked familiarity with South Korea\'s political culture and the National Election Commission\'s vote counting method, misinterpreting the data as showing nearly 100% early voter turnout in certain districts, when the true rate averaged 27%. The Korea Times also pointed out that early voting in 2020 w'), Document(metadata={'title': 'Christian democracy', 'summary': 'Christian democracy is an ideology inspired by Christian social teaching to respond to the challenges of contemporary society and politics.\nChristian democracy has drawn mainly from Catholic social teaching and neo-scholasticism, as well as the Neo-Calvinist tradition within Christianity; it later gained ground with Lutherans and Pentecostals, among other denominational traditions of Christianity in various parts of the world. During the nineteenth century, its principal concerns were to reconcile Catholicism with democracy, to answer the "social question" surrounding capitalism and the working class, and to resolve the tensions between church and state. In the twentieth century, Christian democrats led postwar Western and Southern Europe in building modern welfare states and constructing the European Union. Furthermore; in the late twentieth and early twenty-first century, Christian democracy has gained support in Eastern Europe among former communist states suffering from corruption and stagnation.\nOn the European left-right political spectrum, Christian democracy has been difficult to pinpoint, as Christian democrats have often rejected liberal economics and individualism and advocated state intervention, while simultaneously defending private property rights against excessive state intervention. This has meant that Christian democracy has historically been considered centre-left on economics and centre-right on many social and moral issues. More recently, Christian democrats have positioned themselves as the centre-right; as with both the European People\'s Party and European Christian Political Party, with which many Christian democratic parties in Europe are affiliated. Christian democrats support a "slightly regulated market economy", featuring an effective social security system, thus a social market economy.\nWorldwide, many Christian democratic parties are members of the Centrist Democrat International. Examples of major Christian democratic parties include the Christian Democratic Union of Germany, the Dutch Christian Democratic Appeal, The Centre in Switzerland, the Spanish People\'s Party, the Mexican National Action Party, the Austrian People\'s Party, and the Christian Democratic Party of Chile. Many Christian democratic parties in the Americas are affiliated with the Christian Democrat Organization of America.\nChristian democracy continues to be influential in Europe and Latin America, although it is also present in other parts of the world.', 'source': 'https://en.wikipedia.org/wiki/Christian_democracy'}, page_content='Christian democracy is an ideology inspired by Christian social teaching to respond to the challenges of contemporary society and politics.\nChristian democracy has drawn mainly from Catholic social teaching and neo-scholasticism, as well as the Neo-Calvinist tradition within Christianity; it later gained ground with Lutherans and Pentecostals, among other denominational traditions of Christianity in various parts of the world. During the nineteenth century, its principal concerns were to reconcile Catholicism with democracy, to answer the "social question" surrounding capitalism and the working class, and to resolve the tensions between church and state. In the twentieth century, Christian democrats led postwar Western and Southern Europe in building modern welfare states and constructing the European Union. Furthermore; in the late twentieth and early twenty-first century, Christian democracy has gained support in Eastern Europe among former communist states suffering from corruption and stagnation.\nOn the European left-right political spectrum, Christian democracy has been difficult to pinpoint, as Christian democrats have often rejected liberal economics and individualism and advocated state intervention, while simultaneously defending private property rights against excessive state intervention. This has meant that Christian democracy has historically been considered centre-left on economics and centre-right on many social and moral issues. More recently, Christian democrats have positioned themselves as the centre-right; as with both the European People\'s Party and European Christian Political Party, with which many Christian democratic parties in Europe are affiliated. Christian democrats support a "slightly regulated market economy", featuring an effective social security system, thus a social market economy.\nWorldwide, many Christian democratic parties are members of the Centrist Democrat International. Examples of major Christian democratic parties include the Christian Democratic Union of Germany, the Dutch Christian Democratic Appeal, The Centre in Switzerland, the Spanish People\'s Party, the Mexican National Action Party, the Austrian People\'s Party, and the Christian Democratic Party of Chile. Many Christian democratic parties in the Americas are affiliated with the Christian Democrat Organization of America.\nChristian democracy continues to be influential in Europe and Latin America, although it is also present in other parts of the world.\n\n\n== Overview of political viewpoints ==\nAs a generalization, it can be said that Christian democratic parties in Europe tend to be moderately conservative and, in several cases, form the main conservative party in their respective countries (e.g., in Germany, Spain, Belgium, and Switzerland), such as the Christian Democratic People\'s Party of Switzerland, the Christian Social Party, the Evangelical People\'s Party of Switzerland and the Federal Democratic Union of Switzerland. By contrast, Christian democratic parties in Latin America tend to vary in their position on the political spectrum depending on the country they are in, being either more left-leaning, as in the case of the Christian Democratic Party in Chile, or more right-leaning, as in the case of the National Action Party in Mexico. Geoffrey K. Roberts and Patricia Hogwood have noted that "Christian democracy has incorporated many of the views held by liberals, conservatives and socialists within a wider framework of moral and Christian principles."\nChristian democrats are usually socially conservative and generally have a relatively skeptical stance towards abortion and same-sex marriage, although some Christian democratic parties have accepted the limited legalization of both. They advocate for a consistent life ethic concerning their opposition to capital punishment and assisted suicide. Christian democrats have also supported the prohibition of drugs. Christian democratic parties are often likely to assert their ')]
제공된 문맥에 따르면, 이재명은 2025년 대통령 선거에서 승리한 후 대한민국의 대통령입니다.

### Vector Store as Retriever

In [ ]:
from abc import ABC
from typing import Any
# from langchain_core.retrievers import VectorStoreRetriever

from langchain_core.callbacks import CallbackManagerForRetrieverRun


class VectorStoreRetriever(BaseRetriever):
    def __init__(self, vector_store, tags: list[str] = None, **kwargs: Any):
        super().__init__(**kwargs)
        self.vector_store = vector_store
        self.tags = tags or []

    def _get_relevant_documents(self, query, *, run_manager: CallbackManagerForRetrieverRun, **kwargs: Any) -> list[Document]:
        return self.vector_store.similarity_search(query, **kwargs)


class VectorStore(ABC):
    def as_retriever(self, **kwargs: Any) -> VectorStoreRetriever:
        raise VectorStoreRetriever(vector_store=self, **kwargs)

In [29]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_google_genai import GoogleGenerativeAIEmbeddings
embeddings = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")
#  embeddings = HuggingFaceEmbeddings(model_name="Qwen/Qwen3-Embedding-0.6B")

vector_store = InMemoryVectorStore(embeddings)

docs = [
    Document(page_content='2025년 6월 3일에 당선된 제 21대 대통령은 더불어민주당 이재명이다.',
             metadata={'source': 'https://example.com'}),
    Document(page_content='삼성 가우스는 삼성전자의 멀티모달 모델의 생성형 인공지능이다.',
             metadata={'source': 'https://example.com'}),
]
vector_store.add_documents(docs)

similar_docs = vector_store.similarity_search('한국의 대통령은?', k=2)
print(similar_docs)

prompt = PromptTemplate.from_template("""
다음의 context를 읽고, 질문에 답해줘.
context: {context}
질문: {question}
""")

llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")
chain = {
    'context': vector_store.as_retriever(),
    'question': RunnablePassthrough()
} | prompt | llm

response = chain.invoke('한국의 대통령은?')
print(response.content)

[Document(id='38392d7b-e05b-41c0-b474-f83c7a345a5f', metadata={'source': 'https://example.com'}, page_content='삼성 가우스는 삼성전자의 멀티모달 모델의 생성형 인공지능이다.'), Document(id='3a26a025-7da4-4e72-a405-bf457a4c7188', metadata={'source': 'https://example.com'}, page_content='2025년 6월 3일에 당선된 제 21대 대통령은 더불어민주당 이재명이다.')]
한국의 대통령은 더불어민주당 이재명입니다.

### Web Base Loader

In [36]:
from langchain_google_genai import ChatGoogleGenerativeAI
import bs4
import os
from langchain_community.document_loaders import WebBaseLoader

os.environ["USER_AGENT"] = "Mozilla/5.0"

loader = WebBaseLoader(
    web_path="https://n.news.naver.com/article/001/0015568637",
    bs_kwargs=dict(
        parse_only=bs4.SoupStrainer('article')
    )
)

docs = loader.load()
#  print(docs[0].page_content)

llm = ChatGoogleGenerativeAI(model='gemini-2.0-flash')

response = llm.invoke(f'다음 기사를 한 문장으로 요약해줘 : {docs[0].page_content}')
print(response.content)

오픈AI의 최신 모델 GPT-5가 기대 이하의 성능으로 오류와 잘못된 답변을 연발하며 사용자들의 조롱을 받고, 이전 버전으로 되돌리는 소동까지 벌어졌다.

### PyPDFLoader

In [ ]:
# pip install pypdf
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("data\\AI 에이전트 동향.pdf", mode='single')
docs = loader.load()

with open("data\\AI 에이전트 동향.txt", "w", encoding="utf-8") as f:
    f.write(docs[0].page_content)

### RecursiveCharacterTextSplitter

In [ ]:
with open('data\\AI 에이전트 동향.txt', 'r', encoding='utf-8') as f:
    file = f.read()

from langchain_text_splitters import CharacterTextSplitter, RecursiveCharacterTextSplitter
splitter = RecursiveCharacterTextSplitter()

docs = splitter.create_documents([file])

with open('data\\AI 에이전트 동향_splitted.txt', 'w', encoding='utf-8') as f:
    f.write(f'Number of splitted documents: {len(docs)}')
    for doc in docs:
        f.write(f'\n\n---\n\n{doc.page_content}')

### MarkdownHeaderTextSplitter

In [22]:
with open('data\\langchain.md', 'r', encoding='utf-8') as f:
    file = f.read()

from langchain_text_splitters import MarkdownHeaderTextSplitter
splitter = MarkdownHeaderTextSplitter(
    headers_to_split_on=[('#', 'Chapter'), ('##', 'Section')],
    strip_headers=False,
)

docs = splitter.split_text(file)
for i, doc in enumerate(docs):
    print(i, 'th\n', doc.page_content[:100])

0 th
 # Introduction
**LangChain** is a framework for developing applications powered by large language
1 th
 ## Architecture
The LangChain framework consists of multiple open-source libraries. Read more in t
2 th
 ## Guides
### [Tutorials](/docs/tutorials)
If you're looking to build something specific or are
3 th
 ## Ecosystem
### [🦜🛠️ LangSmith](https://docs.smith.langchain.com)
Trace and evaluate your languag
4 th
 ## Additional resources
### [Versions](/docs/versions/v0_3/)
See what changed in v0.3, learn how t

### SemanticChunker

In [31]:
from langchain_experimental.text_splitter import SemanticChunker
from langchain_google_genai import GoogleGenerativeAIEmbeddings
embeddings = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")

# pip install langchain_experimental
splitter = SemanticChunker(
    embeddings,
    breakpoint_threshold_type='percentile',
    breakpoint_threshold_amount=50,
)

docs = splitter.create_documents([file])
for i, doc in enumerate(docs):
    print(i, 'th\n', doc.page_content[:50])

0 th
 # Introduction

**LangChain** is a framework for d
1 th
 - **Deployment**: Turn your LangGraph applications
2 th
 See the [integrations](/docs/integrations/provider
3 th
 import ChatModelTabs from "@theme/ChatModelTabs";

4 th
 :::

## Architecture

The LangChain framework cons
5 th
 Read more in the
[Architecture](/docs/concepts/arc
6 th
 - **Integration packages** (e.g. `langchain-openai
7 th
 - **`langchain-community`**: Third-party integrati
8 th
 See [LangGraph documentation](https://langchain-ai
9 th
 ## Guides

### [Tutorials](/docs/tutorials)

If yo
10 th
 This is the best place to get started. These are t
11 th
 ### [How-to guides](/docs/how_to)

[Here](/docs/ho
12 th
 These how-to guides don’t cover topics in depth –
13 th
 ### [Conceptual guide](/docs/concepts)

Introducti
14 th
 For a deeper dive into LangGraph concepts, check o
15 th
 If you're looking to get up and running quickly wi
16 th
 ## Ecosystem

### [🦜🛠️ LangSmith](https://docs.smi
17 th
 ### [🦜🕸️ LangGraph](https://langchain-ai.github.io
18 th
 Integrates smoothly with LangChain, but can be use
19 th
 ### [Security](/docs/security)
Read up on [securit

### LLM Splitter

In [ ]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.runnables import RunnablePassthrough
with open('data\\AI 에이전트 동향.txt', 'r', encoding='utf-8') as f:
    file = f.read()

from langchain_core.prompts import PromptTemplate
prompt = PromptTemplate.from_template('''
다음의 context를 읽고, 질문에 답해줘.
context: {context}
질문: {question}
''')

llm = ChatGoogleGenerativeAI(model='gemini-2.0-flash')

# print(file)
chain = {
    'context': lambda x: file,
    'question': RunnablePassthrough(),
} | prompt | llm
response = chain.invoke('AI 에이전트 동향에 대해 5줄로 줄바꿈해서 보기쉽고 간략하게 정리해서 알려줘')
print(response.content)

AI 에이전트는 생성형 AI 확산과 함께 관심이 급증하며, 향후 시장이 빠르게 성장할 것으로 예상됩니다. 빅테크 기업들이 AI 에이전트 시장에 진출하여 다양한 수익 모델을 창출하고 있지만, 기술적, 사회적, 윤리적, 법적 문제도 내포하고 있습니다. AI 에이전트는 고객 서비스, 개인 비서, 자율 주행 차량 등 다양한 산업에 활용될 수 있으며, 개인화 서비스와 실시간 대응 등 혁신적인 서비스를 제공할 수 있습니다. Markets&Markets는 전 세계 AI 에이전트 시장이 2024년 51억 달러에서 2030년 471억 달러로 성장할 것으로 전망했습니다. Gartner는 2025년 최상위 10대 전략 기술 트렌드에서 AI 에이전트를 최우선 기술로 제시하며, 2028년까지 엔터프라이즈 소프트웨어 애플리케이션의 33%에 에이전트 AI가 포함될 것으로 예상했습니다.

### 과제
- file 정보 주고 prompt를 통해 정보 정리 요청청
- 결과를 받아서 vector db에 저장
- vector db 를 retriever로 써서 질문 답변변

In [ ]:
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.runnables import RunnablePassthrough
from pydantic import BaseModel, Field, ValidationError
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.documents import Document
from langchain_core.vectorstores import InMemoryVectorStore
from langchain_core.exceptions import OutputParserException
import re
from typing import Any
import json


class RobustPydanticOutputParser(PydanticOutputParser):
    """
    LLM 출력 또는 Python 객체를 Pydantic 모델로 안전하게 변환하는 파서.
    - 문자열: 후처리(clean ```json) 후 parse
    - list/dict: 바로 Pydantic 객체로 변환
    - JSON 형식 강제 검사 및 ValidationError 처리
    """

    def parse(self, obj: Any):
        # 이미 list/dict이면 바로 Pydantic 객체 생성
        if isinstance(obj, (list, dict)):
            try:
                return self.pydantic_object.parse_obj(obj)
            except ValidationError as e:
                raise OutputParserException(
                    f"Validation failed on Python object: {e}\nInput: {obj}")

        # 문자열이면 후처리
        if isinstance(obj, str):
            # ```json 제거 및 공백 strip
            cleaned = re.sub(r"```json|```", "", obj).strip()
            # JSON 형식인지 강제 검사
            try:
                data = json.loads(cleaned)
            except json.JSONDecodeError as e:
                raise OutputParserException(
                    f"Invalid JSON format after cleaning: {e}\nCleaned text: {cleaned}")

            # Pydantic 객체 생성
            try:
                return self.pydantic_object.parse_obj(data)
            except ValidationError as e:
                raise OutputParserException(
                    f"Pydantic validation failed: {e}\nData: {data}")

        raise OutputParserException(f"Unsupported input type: {type(obj)}")


with open('data\\AI 에이전트 동향_short.txt', 'r', encoding='utf-8') as f:
    file = f.read()

prompt = PromptTemplate.from_template('''
다음의 context 를 읽고, 의미있는 단위로 쪼개서 반드시 format 예제와 같은 형식으로 답해주세요. 

context: {context}
format: 
[
  {{"title": "제목", "content": "내용"}},
  ...
]

모든 content는 반드시 내용이 있어야 하며, null이 되면 안됩니다.
절대로 ```json 같은 코드 블록을 사용하지 마세요.  
오직 [ ... ] JSON 배열 형식으로만 답하세요.  
다른 텍스트, 설명, 마크다운은 금지입니다.
''')


class MeaningfulChunk(BaseModel):
    title: str = Field(description="제목")
    content: str = Field(description="내용")


class MeaningfulChunkList(BaseModel):
    chunks: list[MeaningfulChunk] = Field(description="의미있는 단위로 쪼개진 콘텐츠 목록")


output_parser = RobustPydanticOutputParser(pydantic_object=MeaningfulChunkList)

llm = ChatGoogleGenerativeAI(model='gemini-2.5-flash')

# print(file)
chain = {
    'context': lambda x: file,
    # 'format': lambda x: output_parser.get_format_instructions()
} | prompt | llm  # | output_parser
response = chain.invoke({})

output_parser.parse(response.content)

C:\Users\usejen_id\AppData\Local\Temp\ipykernel_4008\2690495260.py:39: PydanticDeprecatedSince20: The `parse_obj` method is deprecated; use `model_validate` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
  return self.pydantic_object.parse_obj(data)

OutputParserException: Pydantic validation failed: 1 validation error for MeaningfulChunkList
  Input should be a valid dictionary or instance of MeaningfulChunkList [type=model_type, input_value=[{'title': 'AI 에이전... 주도할 것이다.'}], input_type=list]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
Data: [{'title': 'AI 에이전트 동향 개요', 'content': '최근 생성형 AI의 확산과 함께 인간과 상호작용이 가능한 AI 에이전트에 대한 관심이 급증하고 있으며, 향후 몇 년 안에 관련 시장이 급속히 성장할 것으로 예상된다. 빅테크 기업들이 AI 에이전트 시장에 잇따라 진출하며 다양한 수익 모델을 창출하고 있는 상황이다. 그러나 AI 에이전트는 기술적, 사회적, 윤리적, 법적 문제를 초래할 가능성도 내포하고 있다. 앞으로 AI 에이전트는 기술 혁신과 사회 변화를 주도하는 핵심 요소로 자리 잡으며, 기업의 업무방식과 개인의 삶에 깊숙이 통합되어 획기적인 변화를 이끌어갈 것으로 전망된다.'}, {'title': 'AI 에이전트 정의 (학술적 관점)', 'content': 'AI 에이전트에 대한 합의된 학술적 정의는 부재하나, 관련 연구에서는 AI 에이전트를 단순한 AI 모델이나 알고리즘과 구별하여 설명하며, 특히 상호작용과 독립적인 의사결정 능력을 강조한다. 스튜어트 러셀(Stuart Russell)과 피터 노비그(Peter Norvig)는 2021년 저서 ‘인공지능 – 현대적 접근법’에서 에이전트(Agent)는 센서를 통해 환경을 인식하고 센서가 액추에이터를 통해 해당 환경에 작용하는 것으로, 합리적 에이전트(Rational Agent)는 최선의 결과를 달성하기 위해 행동하거나, 불확실성이 있는 경우 최선의 기대 결과를 얻기 위해 행동하는 행위자로 정의했다. 알란 찬(ALan Chan) 등은 2024년 연구논문인 ‘AI 에이전트에 대한 가시성’에서 많은 AI 개발자들이 더 큰 자율성, 외부 도구나 서비스 접근, 장기적 목표 달성을 위해 안정적으로 적응하고 계획하며 지속적 행동할 수 있는 능력 향상을 갖춘 시스템을 제작하고 있다고 설명하면서 이러한 시스템에 대해 AI 에이전트(AI agents 또는 agentic systems)라고 지칭했다.'}, {'title': 'AI 에이전트 정의 (가트너)', 'content': '가트너는 AI 에이전트를 ‘에이젠틱 AI(Agentic AI)’로 칭하고, AI 기술을 사용하여 작업을 완료하고 목표를 달성하는 목표 중심 소프트웨어 엔터티로 정의한다. ‘에이젠틱 AI’는 명시적인 입력 없이 지침을 받고, 계획을 세우고, 도구를 사용하여 작업을 완료하며, 미리 정해진 출력을 생성하지 않고, 동적 출력을 생성할 수 있다고 설명한다. AI 에이전시 스펙트럼을 제시하면서 한쪽 끝에는 특정 작업을 제한적으로 수행하는 전통적인 시스템이 있고, 반대편에는 환경에서 학습하고 독립적으로 결정 및 작업을 수행할 수 있는 완전한 에이전틱 AI 시스템이 있다고 설명한다.'}, {'title': 'AI 에이전트 정의 (ISO/IEC)', 'content': 'ISO/IEC는 AI 관련 표준에서 에이전트(Agent)와 AI 에이전트(AI Agent)를 구분하여 정의한다. 에이전트(Agent)는 ‘환경을 인식하고 목표를 달성하기 위해 조치를 취하는 자동화된 엔티티’라고 정의하고, AI 에이전트(AI Agent)는 “AI 기술을 사용하여 목표를 성공적으로 달성할 가능성을 최대화하는 에이전트”라고 정의한다(ISO/IEC DIS 22989). (ISO/IEC 22989에서 AI 시스템은 "인간이 정의한 목표에 대해 콘텐츠, 예측, 권장 사항 또는 결정과 같은 출력을 생성하는 엔지니어링 시스템"이라고 정의된다.)'}, {'title': 'AI 에이전트 정의 (기업 관점)', 'content': 'AI 에이전트 관련 기능을 제공하는 기업들은 AI 에이전트(또는 유사 개념)를 기업의 특성을 반영하여 다양한 방식으로 정의한다. 세일즈포스는 AI 에이전트를 “인간의 개입 없이 고객 문의를 이해하고 응답할 수 있는 일종의 인공지능 시스템”으로 정의한다. IBM은 AI 에이전트를 ‘워크플로를 설계하고 사용 가능한 도구를 활용하여 사용자 또는 다른 시스템을 대신하여 작업을 자율적으로 수행할 수 있는 시스템이나 프로그램’으로 정의한다.'}, {'title': 'AI 에이전트 부상 배경 (기술 발전 및 수요 확대)', 'content': 'AI 에이전트는 AI 기술이 발전함에 따라 점차 많은 관심을 받고 있다. 클라우드 컴퓨팅과 엣지 컴퓨팅의 발전은 AI 에이전트가 실시간으로 데이터를 처리하고 빠르게 의사결정을 내릴 수 있도록 지원하며, 강화 학습(reinforcement learning), 자연어 처리(NLP), 컴퓨터 비전 등의 분야에서 AI 알고리즘이 발전하면서, AI 에이전트가 더욱 정교한 의사결정을 수행하고 다양한 상황에서 유연한 대응이 가능하다. 고객서비스, 스마트홈, 산업 자동화 등에서 사용자와의 자연스러운 상호작용을 요구하는 환경이 늘어나면서 AI 에이전트의 수요가 확대되고 있다.'}, {'title': 'AI 에이전트 부상 배경 (시장 기회 및 가치 창출)', 'content': 'AI 에이전트 관련 새로운 시장 기회와 가능성에 대한 기대가 증대되고 있다. AI 에이전트는 고객 서비스와 개인 비서, 자율 주행 차량, 스마트 팩토리 등 다양한 산업에 활용될 수 있어서 시장 기회 확대가 예상된다. AI 에이전트는 개인화 서비스, 실시간 대응 및 상호작용 등 기존 기술로는 구현하기 어려운 혁신적인 서비스를 제공하여 새로운 부가 가치 창출이 가능하다. AI 에이전트 개발은 AI 기술의 발전뿐 아니라 데이터 과학, 컴퓨팅 하드웨어, 클라우드 인프라 등의 다양한 기술 생태계의 성장과도 밀접하게 연관되어 기술적, 경제적 성장 기회 창출이 전망된다.'}, {'title': 'AI 에이전트 시장 전망 (Markets&Markets)', 'content': '시장조사기관인 Markets&Markets는 전 세계 AI 에이전트 시장이 2024년 51억 달러에서 2030년 471억 달러로 빠르게 성장할 것으로 예상하고, 연평균 성장률(CAGR)은 44.8%로 전망한다. AI 에이전트들이 더욱 정교한 상호작용과 맥락 인식을 가능하게 하여 고객 서비스, 의료, 금융 분야에서의 활용이 증가하고, 다중 에이전트 시스템의 협력이 AI 시장 성장으로 주요 요인으로 작용한다. AI 에이전트는 주로 NLP, 머신러닝, 컴퓨터 비전 등을 포함하며, 완전 자율부터 반자율 형태로 다양한 업무 자동화와 데이터 분석을 지원하는 소프트웨어로 사용된다.'}, {'title': 'AI 에이전트 시장 전망 (Grand View Research)', 'content': '또 다른 시장조사기관인 Grand View Research도 글로벌 AI 에이전트 시장 규모를 2023년에 38억 6천만 달러로 추정하고, 2024년에서 2030년까지 연평균 성장률(CAGR) 45.1%로 성장할 것으로 예상한다. 개인화된 상호작용에 대한 소비자 기대, 데이터 활용을 통한 맞춤형 추천과 고객 지원, 전자 상거래와 의료 분야에서의 고객 참여 및 운영 간소화 등이 AI 에이전트 시장 성장의 주요 동인으로 작용한다. 또한 보안 시스템에서의 실시간 위협 대응과 이상 감지, 머신러닝 및 NLP 기술의 발전이 AI 에이전트 기능 향상에 기여하여, 복잡한 작업에서도 AI 에이전트의 도입이 증가하고 있다.'}, {'title': 'AI 에이전트 시장 전망 (Grand View Research - 지역 및 산업별)', 'content': 'Grand View Research는 AI 에이전트의 시장에서 지역별로는 북미 지역, 산업별로는 의료산업이 시장 성장을 주도할 것으로 분석한다. 북미 AI 에이전트 시장은 2023년 40.0%가 넘는 매출 점유율로 글로벌 산업을 주도했으며, Google, Microsoft, IBM Corporation을 포함한 주요 기술 회사가 AI 에이전트 기술 개발을 선도하고, 스타트업 생태계를 보유하고 있어 금융 및 교육과 같은 다양한 부문에서 AI 에이전트 발전을 촉진한다. 의료 부문은 2030년까지 가장 높은 CAGR을 보일 것으로 예상되며, 환자 참여 개선, 운영 효율성, 향상된 진단 및 의사 결정 지원, 웨어러블 기기와의 통합과 같은 다양한 요인이 의료 부문의 성장을 주도할 것이다.'}]
For troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/OUTPUT_PARSING_FAILURE

In [44]:
print(len(parsed_data))
print(json.dumps(parsed_data, ensure_ascii=False, indent=2))

18
[
  {
    "title": "문서 정보",
    "content": "SPRi AI Brief Special | 2024년 12월호"
  },
  {
    "title": "AI 에이전트 동향",
    "content": "최근 생성형 AI의 확산과 함께 인간과 상호작용이 가능한 AI 에이전트에 대한 관심이 급증하고 있으며, 향후 몇 년 안에 관련 시장이 급속히 성장할 것으로 예상된다. 빅테크 기업들이 AI 에이전트 시장에 잇따라 진출하며 다양한 수익 모델을 창출하고 있는 상황이다. 그러나 AI 에이전트는 기술적, 사회적, 윤리적, 법적 문제를 초래할 가능성도 내포하고 있다. 앞으로 AI 에이전트는 기술 혁신과 사회 변화를 주도하는 핵심 요소로 자리 잡으며, 기업의 업무방식과 개인의 삶에 깊숙이 통합되어 획기적인 변화를 이끌어갈 것으로 전망된다."
  },
  {
    "title": "1. AI 에이전트(AI Agent)의 도입 및 부상",
    "content": ""
  },
  {
    "title": "1) AI 에이전트의 정의",
    "content": "AI 에이전트에 대한 합의된 학술적 정의는 부재하나, 관련 연구에서는 AI 에이전트를 단순한 AI 모델이나 알고리즘과 구별하여 설명하며, 특히 상호작용과 독립적인 의사결정 능력을 강조"
  },
  {
    "title": "AI 에이전트 정의 - 스튜어트 러셀 & 피터 노비그",
    "content": "스튜어트 러셀(Stuart Russell)과 피터 노비그(Peter Norvig)는 2021년 출판한 저서 ‘인공지능 – 현대적 접근법’에서 에이전트(Agent)는 센서를 통해 환경을 인식하고 센서가 액추에이터를 통해 해당 환경에 작용하는 것으로, 합리적 에이전트(Rational Agent)는 최선의 결과를 달성하기 위해 행동하거나, 불확실성이 있는 경우 최선의 기대 결과를 얻기 위해 행동하는 행위자로 정의"
  },
  {
    "title": "AI 에이전트 정의 - 알란 찬 외",
    "content": "알란 찬(ALan Chan) 등은 2024년 발간된 연구논문인 ‘AI 에이전트에 대한 가시성’에서 많은 AI 개발자들이 더 큰 자율성, 외부 도구나 서비스 접근, 장기적 목표 달성을 위해 안정적으로 적응하고 계획하며 지속적 행동할 수 있는 능력 향상을 갖춘 시스템을 제작하고 있다고 설명하면서 이러한 시스템에 대해 AI 에이전트(AI agents 또는 agentic systems)라고 지칭"
  },
  {
    "title": "AI 에이전트 정의 - 가트너",
    "content": "가트너는 AI 에이전트를 ‘에이젠틱 AI(Agentic AI)’로 칭하고, AI 기술을 사용하여 작업을 완료하고 목표를 달성하는 목표 중심 소프트웨어 엔터티로 정의한다. '에이젠틱 AI’는 명시적인 입력 없이 지침을 받고, 계획을 세우고, 도구를 사용하여 작업을 완료하며, 미리 정해진 출력을 생성하지 않고, 동적 출력을 생성할 수 있다고 설명한다. AI 에이전트 스펙트럼을 제시하면서 한쪽 끝에는 특정 작업을 제한적으로 수행하는 전통적인 시스템이 있고, 반대편에는 환경에서 학습하고 독립적으로 결정 및 작업을 수행할 수 있는 완전한 에이전틱 AI 시스템이 있다고 설명한다."
  },
  {
    "title": "AI 에이전트 정의 - ISO/IEC",
    "content": "ISO/IEC는 AI 관련 표준에서 에이전트(Agent)와 AI 에이전트(AI Agent)를 구분하여 정의한다. 에이전트(Agent)는 ‘환경을 인식하고 목표를 달성하기 위해 조치를 취하는 자동화된 엔티티’라고 정의하고, AI 에이전트(AI Agent)는 “AI 기술을 사용하여 목표를 성공적으로 달성할 가능성을 최대화하는 에이전트”라고 정의한다.(ISO/IEC DIS 22989) ISO/IEC 22989에서 AI 시스템은 '인간이 정의한 목표에 대해 콘텐츠, 예측, 권장 사항 또는 결정과 같은 출력을 생성하는 엔지니어링 시스템‘이라고 정의한다."
  },
  {
    "title": "AI 에이전트 정의 - 기업",
    "content": "AI 에이전트 관련 기능을 제공하는 기업들은 AI 에이전트(또는 유사 개념)를 기업의 특성을 반영하여 다양한 방식으로 정의한다."
  },
  {
    "title": "AI 에이전트 정의 - 세일즈포스",
    "content": "세일즈포스는 AI 에이전트를 “인간의 개입 없이 고객 문의를 이해하고 응답할 수 있는 일종의 인공지능 시스템”으로 정의한다."
  },
  {
    "title": "AI 에이전트 정의 - IBM",
    "content": "IBM은 AI 에이전트를 ‘워크플로를 설계하고 사용 가능한 도구를 활용하여 사용자 또는 다른 시스템을 대신하여 작업을 자율적으로 수행할 수 있는 시스템이나 프로그램’으로 정의한다."
  },
  {
    "title": "2) AI 에이전트의 부상 배경",
    "content": "AI 에이전트는 AI 기술이 발전함에 따라 점차 많은 관심을 받고 있는 상황이다."
  },
  {
    "title": "AI 에이전트 부상 배경 - 기술 발전",
    "content": "클라우드 컴퓨팅과 엣지 컴퓨팅의 발전은 AI 에이전트가 실시간으로 데이터를 처리하고 빠르게 의사결정을 내릴 수 있도록 지원한다. 강화 학습(reinforcement learning), 자연어 처리(NLP), 컴퓨터 비전 등의 분야에서 AI 알고리즘이 발전하면서, AI 에이전트가 더욱 정교한 의사결정을 수행하고 다양한 상황에서 유연한 대응이 가능하다. 고객서비스, 스마트홈, 산업 자동화 등에서 사용자와의 자연스러운 상호작용을 요구하는 환경이 늘어나면서 AI 에이전트의 수요가 확대"
  },
  {
    "title": "AI 에이전트 부상 배경 - 시장 기회",
    "content": "더불어 AI 에이전트 관련 새로운 시장 기회와 가능성에 대한 기대가 증대된다. AI 에이전트는 고객 서비스와 개인 비서, 자율 주행 차량, 스마트 팩토리 등 다양한 산업에 활용될 수 있어서 시장 기회 확대된다. AI 에이전트는 개인화 서비스, 실시간 대응 및 상호작용 등 기존 기술로는 구현하기 어려운 혁신적인 서비스를 제공하여 새로운 부가 가치 창출 가능하다. AI 에이전트 개발은 AI 기술의 발전뿐 아니라 데이터 과학, 컴퓨팅 하드웨어, 클라우드 인프라 등의 다양한 기술 생태계의 성장과도 밀접하게 연관되어 기술적, 경제적 성장 기회 창출 전망"
  },
  {
    "title": "3) AI 에이전트 시장 전망",
    "content": ""
  },
  {
    "title": "AI 에이전트 시장 전망 - Markets&Markets",
    "content": "시장조사기관인 Markets&Markets는 전 세계 AI 에이전트 시장이 2024년 51억 달러에서 2030년 471억 달러로 빠르게 성장할 것으로 예상하고, 연평균 성장률(CAGR)은 44.8%로 전망한다. AI 에이전트들이 더욱 정교한 상호작용과 맥락 인식을 가능하게 하여 고객 서비스, 의료, 금융 분야에서의 활용이 증가하고, 다중 에이전트 시스템의 협력이 AI 시장 성장으로 주요 요인으로 작용한다. AI 에이전트는 주로 NLP, 머신러닝, 컴퓨터 비전 등을 포함하며, 완전 자율부터 반자율 형태로 다양한 업무 자동화와 데이터 분석을 지원하는 소프트웨어로 사용"
  },
  {
    "title": "AI 에이전트 시장 전망 - Grand View Research",
    "content": "또 다른 시장조사기관인 Grand View Research도 글로벌 AI 에이전트 시장 규모를 2023년에 38억 6천만 달러로 추정하고, 2024년에서 2030년까지 연평균 성장률(CAGR) 45.1%로 성장할 것으로 예상한다. 개인화된 상호작용에 대한 소비자 기대, 데이터 활용을 통한 맞춤형 추천과 고객 지원, 전자 상거래와 의료 분야에서의 고객 참여 및 운영 간소화 등이 AI 에이전트 시장 성장의 주요 동인으로 작용한다. 또한 보안 시스템에서의 실시간 위협 대응과 이상 감지, 머신러닝 및 NLP 기술의 발전이 AI 에이전트 기능 향상에 기여하여, 복잡한 작업에서도 AI 에이전트의 도입이 증가"
  },
  {
    "title": "AI 에이전트 시장 전망 - Grand View Research 지역별/산업별 분석",
    "content": "Grand View Research는 AI 에이전트의 시장에서 지역별로는 북미 지역, 산업별로는 의료산업이 시장 성장을 주도할 것으로 분석한다. (지역) 북미 AI 에이전트 시장은 2023년 40.0%가 넘는 매출 점유율로 글로벌 산업을 주도했으며, Google, Microsoft, IBM Corporation을 포함한 주요 기술 회사가 AI 에이전트 기술 개발을 선도하고, 스타트업 생태계를 보유하고 있어 금융 및 교육과 같은 다양한 부문에서 AI 에이전트 발전을 촉진한다. (산업) 의료 부문은 2030년까지 가장 높은 CAGR을 보일 것으로 예상되며, 환자 참여 개선, 운영 효율성, 향상된 진단 및 의사 결정 지원, 웨어러블 기기와의 통합과 같은 다양한 요인이 의료 부문의 성장을 주도한다."
  }
]

In [ ]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
embeddings = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")

vector_store = InMemoryVectorStore(embeddings)

for data in parsed_data:
    vector_store.add_documents(
        [Document(page_content=data['content'], metadata={'title': data['title']})])

vector_store

ValidationError: 1 validation error for Document
page_content
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type

In [53]:
prompt = PromptTemplate.from_template("""
다음의 context를 읽고, 질문에 답해줘.
답변할 때는 줄바꿈을 적절히 해서 보기 쉽게 해줘.
context: {context}
질문: {question}
""")

llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")
chain = {
    'context': vector_store.as_retriever(),
    'question': RunnablePassthrough()
} | prompt | llm

response = chain.invoke('ISO/IEC에서 정의한 AI 에이전트는?')
print(response.content)

제공된 문서에는 ISO/IEC에서 정의한 AI 에이전트에 대한 정보가 없습니다.

In [30]:
prompt

PromptTemplate(input_variables=['context'], input_types={}, partial_variables={}, template='\n다음의 context 를 읽고, 의미있는 단위로 쪼개서 반드시 format의 JSON 형식으로 답해줘\ncontext: {context}\nformat : \n[\n  {{"title": "제목", "content": "내용"}},\n  ...\n]\n')

In [20]:
output_parser.get_format_instructions()

'The output should be formatted as a JSON instance that conforms to the JSON schema below.\n\nAs an example, for the schema {"properties": {"foo": {"title": "Foo", "description": "a list of strings", "type": "array", "items": {"type": "string"}}}, "required": ["foo"]}\nthe object {"foo": ["bar", "baz"]} is a well-formatted instance of the schema. The object {"properties": {"foo": ["bar", "baz"]}} is not well-formatted.\n\nHere is the output schema:\n```\n{"properties": {"title": {"description": "제목", "title": "Title", "type": "string"}, "content": {"description": "내용", "title": "Content", "type": "string"}}, "required": ["title", "content"]}\n```'

In [34]:
response.content

'```json\n[\n  {"title": "문서 정보", "content": "SPRi AI Brief Special | 2024년 12월호"},\n  {"title": "보고서 제목", "content": "AI 에이전트 동향 – 빅테크 기업의 AI 에이전트 사례를 중심으로"},\n  {"title": "서론", "content": "최근 생성형 AI의 확산과 함께 인간과 상호작용이 가능한 AI 에이전트에 대한 관심이 급증하고 있으며, 향후 몇 년 안에 관련 시장이 급속히 성장할 것으로 예상된다. 빅테크 기업들이 AI 에이전트 시장에 잇따라 진출하며 다양한 수익 모델을 창출하고 있는 상황이다. 그러나 AI 에이전트는 기술적, 사회적, 윤리적, 법적 문제를 초래할 가능성도 내포하고 있다. 앞으로 AI 에이전트는 기술 혁신과 사회 변화를 주도하는 핵심 요소로 자리 잡으며, 기업의 업무방식과 개인의 삶에 깊숙이 통합되어 획기적인 변화를 이끌어갈 것으로 전망된다."},\n  {"title": "1. AI 에이전트(AI Agent)의 도입 및 부상", "content": ""},\n  {"title": "1) AI 에이전트의 정의", "content": "AI 에이전트에 대한 합의된 학술적 정의는 부재하나, 관련 연구에서는 AI 에이전트를 단순한 AI 모델이나 알고리즘과 구별하여 설명하며, 특히 상호작용과 독립적인 의사결정 능력을 강조"},\n  {"title": "스튜어트 러셀과 피터 노비그의 정의", "content": "에이전트(Agent)는 센서를 통해 환경을 인식하고 센서가 액추에이터를 통해 해당 환경에 작용하는 것으로, 합리적 에이전트(Rational Agent)는 최선의 결과를 달성하기 위해 행동하거나, 불확실성이 있는 경우 최선의 기대 결과를 얻기 위해 행동하는 행위자로 정의"},\n  {"title": "알란 찬 등의 정의", "content": "많은 AI 개발자들이 더 큰 자율성, 외부 도구나 서비스 접근, 장기적 목표 달성을 위해 안정적으로 적응하고 계획하며 지속적 행동할 수 있는 능력 향상을 갖춘 시스템을 제작하고 있다고 설명하면서 이러한 시스템에 대해 AI 에이전트(AI agents 또는 agentic systems)라고 지칭"},\n  {"title": "가트너의 정의", "content": "AI 에이전트를 ‘에이젠틱 AI(Agentic AI)’로 칭하고, AI 기술을 사용하여 작업을 완료하고 목표를 달성하는 목표 중심 소프트웨어 엔터티로 정의. ‘에이젠틱 AI’는 명시적인 입력 없이 지침을 받고, 계획을 세우고, 도구를 사용하여 작업을 완료하며, 미리 정해진 출력을 생성하지 않고, 동적 출력을 생성할 수 있다고 설명"},\n  {"title": "가트너의 AI 에이전시 스펙트럼", "content": "한쪽 끝에는 특정 작업을 제한적으로 수행하는 전통적인 시스템이 있고, 반대편에는 환경에서 학습하고 독립적으로 결정 및 작업을 수행할 수 있는 완전한 에이전틱 AI 시스템이 있다고 설명"},\n  {"title": "ISO/IEC의 정의", "content": "에이전트(Agent)는 ‘환경을 인식하고 목표를 달성하기 위해 조치를 취하는 자동화된 엔티티’라고 정의하고, AI 에이전트(AI Agent)는 “AI 기술을 사용하여 목표를 성공적으로 달성할 가능성을 최대화하는 에이전트”라고 정의"},\n  {"title": "ISO/IEC 22989의 AI 시스템 정의", "content": "인간이 정의한 목표에 대해 콘텐츠, 예측, 권장 사항 또는 결정과 같은 출력을 생성하는 엔지니어링 시스템"},\n  {"title": "세일즈포스의 정의", "content": "AI 에이전트를 “인간의 개입 없이 고객 문의를 이해하고 응답할 수 있는 일종의 인공지능 시스템”으로 정의"},\n  {"title": "IBM의 정의", "content": "AI 에이전트를 ‘워크플로를 설계하고 사용 가능한 도구를 활용하여 사용자 또는 다른 시스템을 대신하여 작업을 자율적으로 수행할 수 있는 시스템이나 프로그램’으로 정의"},\n  {"title": "2) AI 에이전트의 부상 배경", "content": "AI 에이전트는 AI 기술이 발전함에 따라 점차 많은 관심을 받고 있는 상황"},\n  {"title": "클라우드/엣지 컴퓨팅 발전의 영향", "content": "클라우드 컴퓨팅과 엣지 컴퓨팅의 발전은 AI 에이전트가 실시간으로 데이터를 처리하고 빠르게 의사결정을 내릴 수 있도록 지원"},\n  {"title": "AI 알고리즘 발전의 영향", "content": "강화 학습(reinforcement learning), 자연어 처리(NLP), 컴퓨터 비전 등의 분야에서 AI 알고리즘이 발전하면서, AI 에이전트가 더욱 정교한 의사결정을 수행하고 다양한 상황에서 유연한 대응이 가능"},\n  {"title": "수요 확대 요인", "content": "고객서비스, 스마트홈, 산업 자동화 등에서 사용자와의 자연스러운 상호작용을 요구하는 환경이 늘어나면서 AI 에이전트의 수요가 확대"},\n  {"title": "새로운 시장 기회 및 기대", "content": "AI 에이전트 관련 새로운 시장 기회와 가능성에 대한 기대가 증대"},\n  {"title": "AI 에이전트의 활용 분야", "content": "고객 서비스와 개인 비서, 자율 주행 차량, 스마트 팩토리 등 다양한 산업에 활용될 수 있어서 시장 기회 확대"},\n  {"title": "부가 가치 창출", "content": "AI 에이전트는 개인화 서비스, 실시간 대응 및 상호작용 등 기존 기술로는 구현하기 어려운 혁신적인 서비스를 제공하여 새로운 부가 가치 창출 가능"},\n  {"title": "기술적/경제적 성장 기회", "content": "AI 에이전트 개발은 AI 기술의 발전뿐 아니라 데이터 과학, 컴퓨팅 하드웨어, 클라우드 인프라 등의 다양한 기술 생태계의 성장과도 밀접하게 연관되어 기술적, 경제적 성장 기회 창출 전망"},\n  {"title": "3) AI 에이전트 시장 전망", "content": ""},\n  {"title": "Markets&Markets 시장 전망", "content": "전 세계 AI 에이전트 시장이 2024년 51억 달러에서 2030년 471억 달러로 빠르게 성장할 것으로 예상하고, 연평균 성장률(CAGR)은 44.8%로 전망"},\n  {"title": "Markets&Markets 성장 요인", "content": "AI 에이전트들이 더욱 정교한 상호작용과 맥락 인식을 가능하게 하여 고객 서비스, 의료, 금융 분야에서의 활용이 증가하고, 다중 에이전트 시스템의 협력이 AI 시장 성장으로 주요 요인으로 작용"},\n  {"title": "AI 에이전트의 기술 요소", "content": "AI 에이전트는 주로 NLP, 머신러닝, 컴퓨터 비전 등을 포함하며, 완전 자율부터 반자율 형태로 다양한 업무 자동화와 데이터 분석을 지원하는 소프트웨어로 사용"},\n  {"title": "Grand View Research 시장 규모 추정 (2023년)", "content": "38억 6천만 달러"},\n  {"title": "Grand View Research 연평균 성장률 (2024-2030)", "content": "45.1%"},\n  {"title": "Grand View Research 시장 성장 동인", "content": "개인화된 상호작용에 대한 소비자 기대, 데이터 활용을 통한 맞춤형 추천과 고객 지원, 전자 상거래와 의료 분야에서의 고객 참여 및 운영 간소화 등이 AI 에이전트 시장 성장의 주요 동인으로 작용"},\n  {"title": "Grand View Research AI 에이전트 기능 향상 기여 요인", "content": "보안 시스템에서의 실시간 위협 대응과 이상 감지, 머신러닝 및 NLP 기술의 발전이 AI 에이전트 기능 향상에 기여하여, 복잡한 작업에서도 AI 에이전트의 도입이 증가"},\n  {"title": "Grand View Research 지역별 및 산업별 시장 주도 분석", "content": "북미 지역, 의료산업이 시장 성장을 주도할 것으로 분석"},\n  {"title": "Grand View Research 북미 시장 분석", "content": "2023년 40.0%가 넘는 매출 점유율로 글로벌 산업을 주도했으며, Google, Microsoft, IBM Corporation을 포함한 주요 기술 회사가 AI 에이전트 기술 개발을 선도하고, 스타트업 생태계를 보유하고 있어 금융 및 교육과 같은 다양한 부문에서 AI 에이전트 발전을 촉진"},\n  {"title": "Grand View Research 의료 부문 분석", "content": "2030년까지 가장 높은 CAGR을 보일 것으로 예상되며, 환자 참여 개선, 운영 효율성, 향상된 진단 및 의사 결정 지원, 웨어러블 기기와의 통합과 같은 다양한 요인이 의료 부문의 성장을 주도"}\n]\n```'

### Embedding

In [ ]:
# pip install sentence-transformers
from sklearn.metrics.pairwise import cosine_similarity
from langchain_huggingface import HuggingFaceEmbeddings

from langchain_google_genai import GoogleGenerativeAIEmbeddings
# embeddings=GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")
embeddings = HuggingFaceEmbeddings(model_name="Qwen/Qwen3-Embedding-0.6B")
docs = [
    "한국의 수도는 서울입니다.",
    "중국의 수도는 북경입니다.",
    "삼성전자의 본사는 수원에 있습니다.",
    "파이썬은 프로그래밍 언어입니다.",
]
query = "한국의 수도는?"
docs = [
    "사과는 빨간색도 있고, 초록색도 있습니다. 나는 빨간 사과는 좋아하지만 초록 사과는 싫어합니다.",
    "바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.",
    "포도는 보라색입니다. 포도는 작고 달콤합니다. 포도는 씨가 있어서 먹기 불편합니다. 나는 포도를 싫어합니다.",
    "나는 낚시를 좋아합니다. 낚시는 물고기를 잡는 재미가 있습니다. 낚시는 자연과 함께하는 활동입니다.",
    "나는 여행을 좋아합니다. 여행을 통해 다양한 과일을 맛볼 수 있습니다.",
]
query = "나는 어떤 과일을 좋아할까요?"
embedded_docs = embeddings.embed_documents(docs)
embedded_query = embeddings.embed_query(query)

similarity = cosine_similarity([embedded_query], embedded_docs)
print(similarity)

[[0.55698943 0.5663046  0.40962162 0.36441505 0.60168509]]

### Bi-Encoder vs. Cross-Encoder

In [ ]:
from langchain_community.cross_encoders import HuggingFaceCrossEncoder
docs = [
    "사과는 빨간색도 있고, 초록색도 있습니다. 나는 빨간 사과는 좋아하지만 초록 사과는 싫어합니다.",
    "바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.",
    "포도는 보라색입니다. 포도는 작고 달콤합니다. 포도는 씨가 있어서 먹기 불편합니다. 나는 포도를 싫어합니다.",
    "나는 낚시를 좋아합니다. 낚시는 물고기를 잡는 재미가 있습니다. 낚시는 자연과 함께하는 활동입니다.",
    "나는 여행을 좋아합니다. 여행을 통해 다양한 과일을 맛볼 수 있습니다.",
]
query = "나는 어떤 과일을 좋아할까요?"
cross_encoder = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
scores = cross_encoder.score([(query, doc) for doc in docs])
print(scores)

c:\yul2ya\llmabok\venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\usejen_id\.cache\huggingface\hub\models--BAAI--bge-reranker-v2-m3. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

[1.8223611e-01 2.8320396e-01 3.9509014e-04 1.7941722e-05 6.6267192e-02]

In [4]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.vectorstores import InMemoryVectorStore
embeddings = HuggingFaceEmbeddings(model_name="Qwen/Qwen3-Embedding-0.6B")
vector_store = InMemoryVectorStore(embeddings)
docs = [
    "사과는 빨간색도 있고, 초록색도 있습니다. 나는 빨간 사과는 좋아하지만 초록 사과는 싫어합니다.",
    "바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.",
    "포도는 보라색입니다. 포도는 작고 달콤합니다. 포도는 씨가 있어서 먹기 불편합니다. 나는 포도를 싫어합니다.",
    "나는 낚시를 좋아합니다. 낚시는 물고기를 잡는 재미가 있습니다. 낚시는 자연과 함께하는 활동입니다.",
    "나는 여행을 좋아합니다. 여행을 통해 다양한 과일을 맛볼 수 있습니다.",
]
query = "나는 어떤 과일을 좋아할까요?"

vector_store.add_texts(docs)
response = vector_store.similarity_search(query, k=3)
print(response)

[Document(id='90e9a254-341f-450f-aa6a-a4e49f052bbd', metadata={}, page_content='나는 여행을 좋아합니다. 여행을 통해 다양한 과일을 맛볼 수 있습니다.'), Document(id='d2eeae01-e3b4-4d2a-b7d7-9afdbb52a9d0', metadata={}, page_content='바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.'), Document(id='309f36a4-1e3f-4f55-809d-0e43f788ecea', metadata={}, page_content='사과는 빨간색도 있고, 초록색도 있습니다. 나는 빨간 사과는 좋아하지만 초록 사과는 싫어합니다.')]

### Contextual Compression Retriever

In [76]:
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder
cross_encoder = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
reranker = CrossEncoderReranker(model=cross_encoder)

compression_retriever = ContextualCompressionRetriever(
    base_compressor=reranker,
    base_retriever=vector_store.as_retriever()
)

prompt = PromptTemplate.from_template("""
다음의 context를 읽고, 질문에 답해줘.
context: {context}
질문: {question}
""")

llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")
chain = {
    'context': vector_store.as_retriever(),
    'question': RunnablePassthrough()
} | prompt | llm

response = chain.invoke('내가 좋아하는 과일은?')
print(response.content)

나는 바나나와 빨간 사과를 좋아합니다.

### Vector Store - Chroma

In [5]:
from langchain_chroma import Chroma
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder
from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name='Qwen/Qwen3-Embedding-0.6B')

# pip install langchain-chroma
vector_store = Chroma.from_texts(
    docs, embeddings, persist_directory="chroma_db"
)
retriever = vector_store.as_retriever()
searched = retriever.invoke("내가 좋아하는 과일은?")
print([s.page_content for s in searched])

['바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.', '바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.', '바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.', '바나나는 노란색입니다. 바나나는 맛있습니다. 나는 바나나를 좋아합니다.']

In [ ]:
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_chroma import Chroma
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CrossEncoderReranker
from langchain_community.cross_encoders import HuggingFaceCrossEncoder
from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(model_name="Qwen/Qwen3-Embedding-0.6B")
vector_store = Chroma(
    embedding_function=embeddings,
    persist_directory="chroma_db"
)
cross_encoder = HuggingFaceCrossEncoder(model_name="BAAI/bge-reranker-v2-m3")
reranker = CrossEncoderReranker(model=cross_encoder)
retriever = ContextualCompressionRetriever(
    base_compressor=reranker, base_retriever=vector_store.as_retriever()
)
prompt = PromptTemplate.from_template("""
다음의 context를 읽고, 질문에 답해줘.
context: {context}
질문: {question}
""")

llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")
chain = {
    'context': retriever,
    'question': RunnablePassthrough()
} | prompt | llm

response = chain.invoke('내가 좋아하는 과일은?')
print(response.content)

나는 바나나를 좋아합니다.

### CSV Loader

In [2]:
from langchain_community.document_loaders.csv_loader import CSVLoader

loader = CSVLoader(file_path='data/restaurant_reviews.csv', encoding='utf-8')

docs = loader.load()

print(f'문서 수 : {len(docs)}')
print(docs[0])

문서 수 : 100
page_content='ID: REST_001
Taste: 60
Ambiance: 60
Service: 65
Worth_the_price: no
Menu_variety: 61
Hygienic: 65
Vegan_options: yes
Smoking_area: yes
Parking: yes
Pet_friendly: no' metadata={'source': 'data/restaurant_reviews.csv', 'row': 0}

### Generate Text Description

In [3]:
import pandas as pd
df = pd.read_csv('data/restaurant_reviews.csv')
df

,ID,Taste,Ambiance,Service,Worth_the_price,Menu_variety,Hygienic,Vegan_options,Smoking_area,Parking,Pet_friendly
0,REST_001,60,60,65,no,61,65,yes,yes,yes,no
1,REST_002,75,71,69,no,78,78,no,yes,no,no
2,REST_003,80,85,79,no,85,85,no,yes,yes,yes
3,REST_004,90,20,90,no,20,50,yes,no,yes,yes
4,REST_005,98,98,98,no,98,98,no,no,no,yes
...,...,...,...,...,...,...,...,...,...,...,...
95,REST_096,22,23,25,no,23,24,yes,yes,yes,no
96,REST_097,21,36,36,no,85,80,yes,no,no,yes
97,REST_098,20,26,31,no,20,90,yes,no,no,no
98,REST_099,65,61,65,no,86,86,yes,yes,no,no
99,REST_100,69,78,78,no,50,90,yes,yes,yes,yes

In [7]:
# pip install pandasdf = pd.read_csv('data/restaurant_reviews.csv')

from langchain_google_genai import ChatGoogleGenerativeAI
import pandas as pd
df = pd.read_csv('data/restaurant_reviews.csv')
llm = ChatGoogleGenerativeAI(model='gemini-2.0-flash')


def score_to_text(score):
    score = int(score)
    if score >= 90:
        return "매우 좋음"
    elif score >= 80:
        return "좋음"
    elif score >= 60:
        return "보통"
    else:
        return "비추"


def generate_description(row):
    desc = f"{row.ID}는 맛 점수 {score_to_text(row.Taste)}, 분위기 {score_to_text(row.Ambiance)}, 서비스 {score_to_text(row.Service)}로 평가됩니다. "
    desc += f"메뉴 다양성은 {score_to_text(row.Menu_variety)}, 위생 점수는 {score_to_text(row.Hygienic)}입니다. "
    desc += f"가격 대비 가치 점수는 {'좋음' if row.Worth_the_price != 'no' else '안좋음'},"
    desc += f"비건옵션: {'있음' if row.Vegan_options == 'yes' else '없음'}, "
    desc += f"흡연구역: {'있음' if row.Smoking_area == 'yes' else '없음'}, "
    desc += f"주차공간: {'있음' if row.Parking == 'yes' else '없음'}, "
    desc += f"반려동물: {'가능' if row.Pet_friendly == 'yes' else '불가'}."
    return desc


df['Description'] = df.apply(generate_description, axis=1)

df.to_csv('data/restaurant_reviews_with_descriptions.csv', index=False)
df

,ID,Taste,Ambiance,Service,Worth_the_price,Menu_variety,Hygienic,Vegan_options,Smoking_area,Parking,Pet_friendly,Description
0,REST_001,60,60,65,no,61,65,yes,yes,yes,no,"REST_001는 맛 점수 보통, 분위기 보통, 서비스 보통로 평가됩니다. 메뉴 다..."
1,REST_002,75,71,69,no,78,78,no,yes,no,no,"REST_002는 맛 점수 보통, 분위기 보통, 서비스 보통로 평가됩니다. 메뉴 다..."
2,REST_003,80,85,79,no,85,85,no,yes,yes,yes,"REST_003는 맛 점수 좋음, 분위기 좋음, 서비스 보통로 평가됩니다. 메뉴 다..."
3,REST_004,90,20,90,no,20,50,yes,no,yes,yes,"REST_004는 맛 점수 매우 좋음, 분위기 비추, 서비스 매우 좋음로 평가됩니다..."
4,REST_005,98,98,98,no,98,98,no,no,no,yes,"REST_005는 맛 점수 매우 좋음, 분위기 매우 좋음, 서비스 매우 좋음로 평가..."
...,...,...,...,...,...,...,...,...,...,...,...,...
95,REST_096,22,23,25,no,23,24,yes,yes,yes,no,"REST_096는 맛 점수 비추, 분위기 비추, 서비스 비추로 평가됩니다. 메뉴 다..."
96,REST_097,21,36,36,no,85,80,yes,no,no,yes,"REST_097는 맛 점수 비추, 분위기 비추, 서비스 비추로 평가됩니다. 메뉴 다..."
97,REST_098,20,26,31,no,20,90,yes,no,no,no,"REST_098는 맛 점수 비추, 분위기 비추, 서비스 비추로 평가됩니다. 메뉴 다..."
98,REST_099,65,61,65,no,86,86,yes,yes,no,no,"REST_099는 맛 점수 보통, 분위기 보통, 서비스 보통로 평가됩니다. 메뉴 다..."
99,REST_100,69,78,78,no,50,90,yes,yes,yes,yes,"REST_100는 맛 점수 보통, 분위기 보통, 서비스 보통로 평가됩니다. 메뉴 다..."

### Store to Vector Store (Chroma)

In [ ]:
from langchain.schema.runnable import RunnablePassthrough
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
import pandas as pd
df = pd.read_csv('data/restaurant_reviews_with_descriptions.csv')

docs = [
    Document(
        page_content=row['Description'],
        metadata={
            key: row[key]
            for key in row.index if key != 'Description'
        }
    )
    for _, row in df.iterrows()
]

# print(docs[0])

embedding = HuggingFaceEmbeddings(model_name='Qwen/Qwen3-Embedding-0.6B')

db = Chroma.from_documents(
    docs, embedding, persist_directory='chroma_restaurant_2'
)

searched = db.similarity_search('주차공간과 흡연공간이 있는 맛점수가 높은 레스토랑은?', k=3)
print([s.page_content for s in searched])

prompt = PromptTemplate.from_template(
    "다음 내용을 참고해서 질문에 답하세요.\n\n참고할 내용:{context}\n\n질문: {question}"
)

llm = ChatGoogleGenerativeAI(model='gemini-2.0-flash')

chain = {
    'context': db.as_retriever(),
    'question': RunnablePassthrough()
} | prompt | llm

response = chain.invoke('주차공간과 흡연공간이 있는 맛점수가 높은 레스토랑은?')
print(response.content)

['REST_005는 맛 점수 매우 좋음, 분위기 매우 좋음, 서비스 매우 좋음로 평가됩니다. 메뉴 다양성은 매우 좋음, 위생 점수는 매우 좋음입니다. 가격 대비 가치 점수는 안좋음,비건옵션: 없음, 흡연구역: 없음, 주차공간: 없음, 반려동물: 가능.', 'REST_071는 맛 점수 매우 좋음, 분위기 매우 좋음, 서비스 매우 좋음로 평가됩니다. 메뉴 다양성은 매우 좋음, 위생 점수는 매우 좋음입니다. 가격 대비 가치 점수는 안좋음,비건옵션: 있음, 흡연구역: 있음, 주차공간: 없음, 반려동물: 불가.', 'REST_073는 맛 점수 매우 좋음, 분위기 매우 좋음, 서비스 매우 좋음로 평가됩니다. 메뉴 다양성은 매우 좋음, 위생 점수는 매우 좋음입니다. 가격 대비 가치 점수는 안좋음,비건옵션: 있음, 흡연구역: 있음, 주차공간: 없음, 반려동물: 불가.']
주어진 정보에서 주차 공간은 없고, 흡연 공간이 있는 레스토랑은 REST_071과 REST_073입니다. 맛 점수는 두 곳 모두 매우 좋습니다.

In [9]:
from langchain_chroma import Chroma
db = Chroma(
    embedding_function=embedding,
    persist_directory='chroma_restaurant_2'
)

searched = db.similarity_search(
    "흡연 구역과 주차장이 있고 맛 평가가 80점 이상인 식당을 추천해줘.", k=3
)
print(searched)

searched = db.similarity_search(
    "흡연 구역과 주차장이 있는 식당을 알려줘.", k=3,
    filter={"Taste": {"$gte": 70}}
)
for s in searched:
    print(s.metadata['ID'], '흡연:', s.metadata['Smoking_area'],
          ' 주차:', s.metadata['Parking'], ' 맛:', s.metadata['Taste'])

[Document(id='844e41cb-af3f-4ed8-806f-100c0b057ef4', metadata={'Hygienic': 36, 'Vegan_options': 'yes', 'Worth_the_price': 'yes', 'Ambiance': 20, 'Menu_variety': 31, 'ID': 'REST_084', 'Pet_friendly': 'yes', 'Service': 20, 'Smoking_area': 'yes', 'Taste': 90, 'Parking': 'yes'}, page_content='REST_084는 맛 점수 매우 좋음, 분위기 비추, 서비스 비추로 평가됩니다. 메뉴 다양성은 비추, 위생 점수는 비추입니다. 가격 대비 가치 점수는 좋음,비건옵션: 있음, 흡연구역: 있음, 주차공간: 있음, 반려동물: 가능.'), Document(id='8fac63b7-436a-4ca5-9cba-63cbf6f0f095', metadata={'Hygienic': 5, 'Pet_friendly': 'yes', 'Menu_variety': 5, 'Taste': 1, 'Vegan_options': 'no', 'Ambiance': 5, 'Parking': 'yes', 'Service': 5, 'Worth_the_price': 'no', 'ID': 'REST_080', 'Smoking_area': 'yes'}, page_content='REST_080는 맛 점수 비추, 분위기 비추, 서비스 비추로 평가됩니다. 메뉴 다양성은 비추, 위생 점수는 비추입니다. 가격 대비 가치 점수는 안좋음,비건옵션: 없음, 흡연구역: 있음, 주차공간: 있음, 반려동물: 가능.'), Document(id='bfab9bc4-62ac-4b09-90fe-a4db5f8e280c', metadata={'Menu_variety': 36, 'Worth_the_price': 'no', 'Parking': 'no', 'Ambiance': 86, 'Smoking_area': 'no', 'ID': 'REST_086', 'Vegan_options': 'no', 'Service': 85, 'Pet_friendly': 'yes', 'Hygienic': 36, 'Taste': 85}, page_content='REST_086는 맛 점수 좋음, 분위기 좋음, 서비스 좋음로 평가됩니다. 메뉴 다양성은 비추, 위생 점수는 비추입니다. 가격 대비 가치 점수는 안좋음,비건옵션: 없음, 흡연구역: 없음, 주차공간: 없음, 반려동물: 가능.')]
REST_055 흡연: yes  주차: yes  맛: 86
REST_071 흡연: yes  주차: no  맛: 100
REST_012 흡연: yes  주차: yes  맛: 80

In [11]:
from langchain_chroma import Chroma
db = Chroma(
    embedding_function=embedding, persist_directory="chroma_db_restaurant",
    collection_name="restaurant_reviews"
)
searched = db.get(
    where={"$and": [
        {"Smoking_area": "yes"},
        {"Parking": "yes"},
        {"Taste": {"$gte": 80}}
    ]
    },
)
print(searched)
for m in searched["metadatas"]:
    print(m)

{'ids': [], 'embeddings': None, 'documents': [], 'uris': None, 'included': ['metadatas', 'documents'], 'data': None, 'metadatas': []}

### Self query retriever

In [13]:
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.retrievers.self_query.base import SelfQueryRetriever
from langchain.chains.query_constructor.base import AttributeInfo

metadata_field_info = [
    AttributeInfo(
        name="Taste",
        description="the taste of the food provided by the restaurant. Rated between 1 to 100",
        type="integer",
    ),
    AttributeInfo(
        name="Ambiance",
        description="the ambiance of the restaurant. Rated between 1 to 100",
        type="integer",
    ),
    AttributeInfo(
        name="Menu_variety",
        description="the Menu_variety of the restaurant. Rated between 1 to 100",
        type="integer",
    ),
    AttributeInfo(
        name="Hygienic",
        description="the Hygienic of the restaurant. Rated between 1 to 100",
        type="integer",
    ),
    AttributeInfo(
        name="Service",
        description="the service of the restaurant. Rated between 1 to 100",
        type="integer",
    ),
    AttributeInfo(
        name="Worth_the_price",
        description="the worth the price of the restaurant. no or yes",
        type="String",
    ),
    AttributeInfo(
        name="Vegan_options",
        description="have the vegan options. no or yes",
        type="String",
    ),
    AttributeInfo(
        name="Smoking_area",
        description="have the smocking area. no or yes",
        type="String",
    ),
    AttributeInfo(
        name="Parking",
        description="have the parking area. no or yes",
        type="String",
    ),
    AttributeInfo(
        name="Pet_friendly",
        description="the pet friendly of the restaurant. no or yes",
        type="String",
    ),
]


llm = ChatGoogleGenerativeAI(model='gemini-2.0-flash')
embeddings = HuggingFaceEmbeddings(model_name="Qwen/Qwen3-Embedding-0.6B")

vector_store = Chroma(embedding_function=embeddings,
                      persist_directory="chroma_restaurant_2")
retriever = SelfQueryRetriever.from_llm(
    llm=llm,
    vectorstore=vector_store,
    document_contents="Restaurant review data",
    metadata_field_info=metadata_field_info,
)

response = retriever.invoke('주차장이 있고 맛 평가가 80점 이상인 식당은?')
for doc in response:
    print(doc.metadata)

{'Worth_the_price': 'no', 'Smoking_area': 'yes', 'Taste': 86, 'Ambiance': 86, 'ID': 'REST_055', 'Service': 86, 'Pet_friendly': 'yes', 'Parking': 'yes', 'Menu_variety': 85, 'Hygienic': 85, 'Vegan_options': 'no'}
{'Worth_the_price': 'no', 'Smoking_area': 'no', 'ID': 'REST_004', 'Hygienic': 50, 'Ambiance': 20, 'Taste': 90, 'Vegan_options': 'yes', 'Pet_friendly': 'yes', 'Menu_variety': 20, 'Parking': 'yes', 'Service': 90}
{'Parking': 'yes', 'Smoking_area': 'no', 'Vegan_options': 'yes', 'Taste': 86, 'Ambiance': 56, 'Service': 54, 'Worth_the_price': 'no', 'Pet_friendly': 'no', 'Menu_variety': 86, 'Hygienic': 86, 'ID': 'REST_042'}
{'Parking': 'yes', 'Vegan_options': 'yes', 'Worth_the_price': 'yes', 'Ambiance': 20, 'Service': 20, 'ID': 'REST_084', 'Pet_friendly': 'yes', 'Taste': 90, 'Menu_variety': 31, 'Hygienic': 36, 'Smoking_area': 'yes'}

In [15]:
from langchain.chains.query_constructor.base import get_query_constructor_prompt
prompt = get_query_constructor_prompt(
    "Restaurant review data",  # 문서 내용 설명
    metadata_field_info,  # 메타데이터 필드 정보
)
prompt.pretty_print()

Your goal is to structure the user's query to match the request schema provided below.

<< Structured Request Schema >>
When responding use a markdown code snippet with a JSON object formatted in the following schema:

```json
{
    "query": string \ text string to compare to document contents
    "filter": string \ logical condition statement for filtering documents
}
```

The query string should contain only text that is expected to match the contents of documents. Any conditions in the filter should not be mentioned in the query as well.

A logical condition statement is composed of one or more comparison and logical operation statements.

A comparison statement takes the form: `comp(attr, val)`:
- `comp` (eq | ne | gt | gte | lt | lte | contain | like | in | nin): comparator
- `attr` (string):  name of attribute to apply the comparison to
- `val` (string): is the comparison value

A logical operation statement takes the form `op(statement1, statement2, ...)`:
- `op` (and | or | not): logical operator
- `statement1`, `statement2`, ... (comparison statements or logical operation statements): one or more statements to apply the operation to

Make sure that you only use the comparators and logical operators listed above and no others.
Make sure that filters only refer to attributes that exist in the data source.
Make sure that filters only use the attributed names with its function names if there are functions applied on them.
Make sure that filters only use format `YYYY-MM-DD` when handling date data typed values.
Make sure that filters take into account the descriptions of attributes and only make comparisons that are feasible given the type of data being stored.
Make sure that filters are only used as needed. If there are no filters that should be applied return "NO_FILTER" for the filter value.

<< Example 1. >>
Data Source:
```json
{
    "content": "Lyrics of a song",
    "attributes": {
        "artist": {
            "type": "string",
            "description": "Name of the song artist"
        },
        "length": {
            "type": "integer",
            "description": "Length of the song in seconds"
        },
        "genre": {
            "type": "string",
            "description": "The song genre, one of "pop", "rock" or "rap""
        }
    }
}
```

User Query:
What are songs by Taylor Swift or Katy Perry about teenage romance under 3 minutes long in the dance pop genre

Structured Request:
```json
{
    "query": "teenager love",
    "filter": "and(or(eq(\"artist\", \"Taylor Swift\"), eq(\"artist\", \"Katy Perry\")), lt(\"length\", 180), eq(\"genre\", \"pop\"))"
}
```


<< Example 2. >>
Data Source:
```json
{
    "content": "Lyrics of a song",
    "attributes": {
        "artist": {
            "type": "string",
            "description": "Name of the song artist"
        },
        "length": {
            "type": "integer",
            "description": "Length of the song in seconds"
        },
        "genre": {
            "type": "string",
            "description": "The song genre, one of "pop", "rock" or "rap""
        }
    }
}
```

User Query:
What are songs that were not published on Spotify

Structured Request:
```json
{
    "query": "",
    "filter": "NO_FILTER"
}
```


<< Example 3. >>
Data Source:
```json
{
    "content": "Restaurant review data",
    "attributes": {
    "Taste": {
        "description": "the taste of the food provided by the restaurant. Rated between 1 to 100",
        "type": "integer"
    },
    "Ambiance": {
        "description": "the ambiance of the restaurant. Rated between 1 to 100",
        "type": "integer"
    },
    "Menu_variety": {
        "description": "the Menu_variety of the restaurant. Rated between 1 to 100",
        "type": "integer"
    },
    "Hygienic": {
        "description": "the Hygienic of the restaurant. Rated between 1 to 100",
        "type": "integer"
    },
    "Service": {
        "description": "the service of the restaurant. Rated between 1 to 100",
        "type": "integer"
    },
    "Worth_the_price": {
        "description": "the worth the price of the restaurant. no or yes",
        "type": "String"
    },
    "Vegan_options": {
        "description": "have the vegan options. no or yes",
        "type": "String"
    },
    "Smoking_area": {
        "description": "have the smocking area. no or yes",
        "type": "String"
    },
    "Parking": {
        "description": "have the parking area. no or yes",
        "type": "String"
    },
    "Pet_friendly": {
        "description": "the pet friendly of the restaurant. no or yes",
        "type": "String"
    }
}
}
```

User Query:
{query}

Structured Request:

In [ ]:
from langchain.chains.query_constructor.base import StructuredQueryOutputParser
from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")
output_parser = StructuredQueryOutputParser.from_components()
query_constructor = prompt | llm | output_parser
query_output = query_constructor.invoke("주차장이 있고 맛 평가가 80점 이상인 식당은?")
print(query_output)

query=' ' filter=Operation(operator=<Operator.AND: 'and'>, arguments=[Comparison(comparator=<Comparator.EQ: 'eq'>, attribute='Parking', value='yes'), Comparison(comparator=<Comparator.GTE: 'gte'>, attribute='Taste', value='80')]) limit=None

In [17]:
from langchain_community.query_constructors.chroma import ChromaTranslator
translator = ChromaTranslator()
filter = translator.visit_operation(query_output.filter)
print(filter)

{'$and': [{'Parking': {'$eq': 'yes'}}, {'Taste': {'$gte': '80'}}]}

In [19]:
from langchain_community.utilities import SQLDatabase
from sqlalchemy import create_engine
import pandas as pd     # Importing pandas for data manipulation
df = pd.read_csv('data/restaurant_reviews.csv')

engine = create_engine("sqlite:///restaurant.db")

df.to_sql("restaurant", engine, if_exists="replace", index=False)

db = SQLDatabase(engine=engine)

print(db.dialect)                   # sqlite
print(db.get_usable_table_names())  # ['restaurant']
print(db.get_table_info())

searched = db.run(
    "SELECT * FROM restaurant WHERE Smoking_Area='yes' and Parking='yes' and Taste >= 80;")
print(eval(searched))       # searched가 문자열이다.
for row in eval(searched):
    print(row[0])

sqlite
['restaurant']

CREATE TABLE restaurant (
	"ID" TEXT,
	"Taste" BIGINT,
	"Ambiance" BIGINT,
	"Service" BIGINT,
	"Worth_the_price" TEXT,
	"Menu_variety" BIGINT,
	"Hygienic" BIGINT,
	"Vegan_options" TEXT,
	"Smoking_area" TEXT,
	"Parking" TEXT,
	"Pet_friendly" TEXT
)

/*
3 rows from restaurant table:
ID	Taste	Ambiance	Service	Worth_the_price	Menu_variety	Hygienic	Vegan_options	Smoking_area	Parking	Pet_friendly
REST_001	60	60	65	no	61	65	yes	yes	yes	no
REST_002	75	71	69	no	78	78	no	yes	no	no
REST_003	80	85	79	no	85	85	no	yes	yes	yes
*/
[('REST_003', 80, 85, 79, 'no', 85, 85, 'no', 'yes', 'yes', 'yes'), ('REST_010', 80, 80, 80, 'yes', 80, 80, 'no', 'yes', 'yes', 'no'), ('REST_012', 80, 99, 74, 'yes', 80, 80, 'yes', 'yes', 'yes', 'yes'), ('REST_055', 86, 86, 86, 'no', 85, 85, 'no', 'yes', 'yes', 'yes'), ('REST_084', 90, 20, 20, 'yes', 31, 36, 'yes', 'yes', 'yes', 'yes')]
REST_003
REST_010
REST_012
REST_055
REST_084

In [21]:
from langchain import hub
prompt = hub.pull("rlm/text-to-sql")
prompt = prompt.partial(table_info=db.get_table_info(), dialect=db.dialect,
                        few_shot_examples="")
print(prompt)
chain = prompt | llm
response = chain.invoke("주차장이 있고 맛 평가가 높은 식당을 3개 찾아줘.")
print(response.content)

input_variables=['input'] input_types={} partial_variables={'table_info': '\nCREATE TABLE restaurant (\n\t"ID" TEXT, \n\t"Taste" BIGINT, \n\t"Ambiance" BIGINT, \n\t"Service" BIGINT, \n\t"Worth_the_price" TEXT, \n\t"Menu_variety" BIGINT, \n\t"Hygienic" BIGINT, \n\t"Vegan_options" TEXT, \n\t"Smoking_area" TEXT, \n\t"Parking" TEXT, \n\t"Pet_friendly" TEXT\n)\n\n/*\n3 rows from restaurant table:\nID\tTaste\tAmbiance\tService\tWorth_the_price\tMenu_variety\tHygienic\tVegan_options\tSmoking_area\tParking\tPet_friendly\nREST_001\t60\t60\t65\tno\t61\t65\tyes\tyes\tyes\tno\nREST_002\t75\t71\t69\tno\t78\t78\tno\tyes\tno\tno\nREST_003\t80\t85\t79\tno\t85\t85\tno\tyes\tyes\tyes\n*/', 'dialect': 'sqlite', 'few_shot_examples': ''} metadata={'lc_hub_owner': 'rlm', 'lc_hub_repo': 'text-to-sql', 'lc_hub_commit_hash': '794179d844347574a2e6012924720bf4beebe35d8229fa632b693807f069d612'} messages=[HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['dialect', 'few_shot_examples', 'input', 'table_info'], input_types={}, partial_variables={}, template='Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer.\nUse the following format:\n\nQuestion: "Question here"\nSQLQuery: "SQL Query to run"\nSQLResult: "Result of the SQLQuery"\nAnswer: "Final answer here"\n\nOnly use the following tables:\n\n{table_info}.\n\nSome examples of SQL queries that corrsespond to questions are:\n\n{few_shot_examples}\n\nQuestion: {input}'), additional_kwargs={})]
SQLQuery: SELECT ID FROM restaurant WHERE Parking = 'yes' ORDER BY Taste DESC LIMIT 3
SQLResult: REST_012
REST_003
REST_014
Answer: REST_012,REST_003,REST_014

## Evaluation

- LLM as Judge
- Lang Smith 
  - Observability 
    - Trace
  - Prompt Engineering
  - Evals

### Generation using RAGAS
- 데이터셋을 만들어 주는 도구

In [28]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_core.vectorstores import InMemoryVectorStore
embeddings = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")

# 저장된 벡터 스토어 파일 경로
path = 'data/ai_trends_vector_store'

# 벡터 스토어 로드
vector_store = InMemoryVectorStore.load(path, embedding=embeddings)
vector_store

In [ ]:
# import dotenv
# dotenv.load_dotenv()

# from langchain_google_genai import ChatGoogleGenerativeAI
# llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash")

# from langchain_huggingface import HuggingFaceEmbeddings
# embeddings = HuggingFaceEmbeddings(model_name="Qwen/Qwen3-Embedding-0.6B")

# # pip install ragas rapidfuzz
# from ragas.testset import TestsetGenerator
# generator = TestsetGenerator.from_langchain(llm, embeddings)

# docs = [Document(page_content=text) for text in texts]

# dataset=generator.generate_with_langchain_docs(docs, testset_size=10)

# df=dataset.to_pandas()
# df.to_csv('ragas/dataset.csv', index=False)

In [ ]:
from ragas.testset import TestsetGenerator
generator=TestsetGenerator(llm=llm_wrapper, embedding_model=embeddings_wrapper)
dataset=generator.generate_with_langchain_docs(docs, testset_size=10)
df=dataset.to_pandas()
df.to_csv('dataset.csv', index=False)
https://docs.ragas.io/en/stable/getstarted/rag_testset_generation

### Examples 등록
평가할 수 있는 예제들

In [29]:
import pandas as pd
from langsmith import Client
from dotenv import load_dotenv
load_dotenv()
client = Client()

dataset = client.create_dataset(
    dataset_name="AGENT_DATASET",
    description="dataset for AI trends"
)

df = pd.read_csv("data/dataset.csv")

examples = [
    {
        "inputs": {"question": row["user_input"]},
        "outputs": {"answer": row["reference"]}
    }
    for _, row in df.iterrows()
]

client.create_examples(dataset_id=dataset.id, examples=examples)

{'example_ids': ['6c9bafc4-7d47-471a-b82f-4c0b3c7bd443',
  '80333e19-8ea1-4a60-a464-09d4875ed4d8',
  '92d056da-30e5-43a6-b8e7-08dba889de0f',
  'e568ff64-b2a8-4700-b718-9bf0bc01ef07',
  '11fc11fd-0750-4ddd-a92b-14b1f1b93394',
  '1506ec80-83be-45e7-95f9-e4c68eb445c8',
  'e3c55591-f60f-44b0-b8d7-718090678500',
  '5af9bc4a-216c-40a3-acff-99a8a63ed87a',
  'a3ce552d-3d56-4561-8954-71a866785fd8',
  'aa7e73ba-4309-48bf-a69d-73917a76e11f',
  'dfa80e9e-6557-4ba9-a04b-dc32162d9811',
  '409faf17-2413-4bff-ab8b-9c2e84b06aed'],
 'count': 12}

In [ ]:
from langsmith.evaluation import evaluate, LangChainStringEvaluator
from langsmith.schemas import Run, Example
from langchain_core.runnables import RunnableLambda
chain = RunnableLambda(lambda x: x)


def my_score_evaluator(run: Run, example: Example) -> dict:
    #   (run.outputs["result"], example.outputs["answer"])로부터 score를 계산
    import random
    return {"key": "my_score", "score": random.randint(1, 11)}   # 랜덤 평가


experiment_results = evaluate(
    lambda inputs: {"result": chain.invoke(inputs["question"])},
    data="AGENT_DATASET",
    evaluators=[my_score_evaluator],
    experiment_prefix="RAG_EVAL",
)

View the evaluation results for experiment: 'RAG_EVAL-5f9f89c6' at:
https://smith.langchain.com/o/3ea1fbac-6bd8-4944-8e26-03912fd4d074/datasets/cd259c5e-5a56-46e9-ac87-97cff47dbae2/compare?selectedSessions=a602001e-d0b0-43d3-8fe5-3d011080a0b1

0it [00:00, ?it/s]

In [38]:
from langsmith.evaluation import evaluate, LangChainStringEvaluator
from langsmith.schemas import Run, Example
from langchain_core.runnables import RunnableLambda
from langchain_google_genai import ChatGoogleGenerativeAI


qa_evalulator = LangChainStringEvaluator("qa", config={"llm": llm})
qa_evalulator.evaluator.prompt.pretty_print()

embeddings = GoogleGenerativeAIEmbeddings(model="models/text-embedding-004")

# 저장된 벡터 스토어 파일 경로
path = 'data/ai_trends_vector_store'

# 벡터 스토어 로드
vector_store = InMemoryVectorStore.load(path, embedding=embeddings)

prompt = PromptTemplate.from_template(
    "다음 내용을 참고해서 질문에 답하세요.\n\n참고할 내용:{context}\n\n질문: {question}"
)

llm = ChatGoogleGenerativeAI(model='gemini-2.0-flash')

chain = {
    'context': vector_store.as_retriever(),
    'question': RunnablePassthrough()
} | prompt | llm

# response = chain.invoke('ai 트렌드에 대해 알려줘')
# response.content
experiment_results = evaluate(
    lambda inputs: {"result": chain.invoke(inputs["question"])},
    data="AGENT_DATASET",
    evaluators=[qa_evalulator],
    experiment_prefix="RAG_EVAL",
)

You are a teacher grading a quiz.
You are given a question, the student's answer, and the true answer, and are asked to score the student answer as either CORRECT or INCORRECT.

Example Format:
QUESTION: question here
STUDENT ANSWER: student's answer here
TRUE ANSWER: true answer here
GRADE: CORRECT or INCORRECT here

Grade the student answers based ONLY on their factual accuracy. Ignore differences in punctuation and phrasing between the student answer and true answer. It is OK if the student answer contains more information than the true answer, as long as it does not contain any conflicting statements. Begin!

QUESTION: {query}
STUDENT ANSWER: {result}
TRUE ANSWER: {answer}
GRADE:
View the evaluation results for experiment: 'RAG_EVAL-9c708054' at:
https://smith.langchain.com/o/3ea1fbac-6bd8-4944-8e26-03912fd4d074/datasets/cd259c5e-5a56-46e9-ac87-97cff47dbae2/compare?selectedSessions=e817ed55-6fa9-4d56-872c-42ff9ee4ec7c

0it [00:00, ?it/s]

Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 4.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 21
}
].
Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 8.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].

In [ ]:
# 간결성 평가
conciseness_evalulator = LangChainStringEvaluator(
    "criteria",
    config={"criteria": "conciseness", "llm": llm}
)
# 관련성 평가
relevance_evalulator = LangChainStringEvaluator(
    "criteria",
    config={"criteria": "relevance", "llm": llm}
)
# 정확성 평가
correctness_evalulator = LangChainStringEvaluator(
    "labeled_criteria",
    config={
        "criteria": "correctness", "llm": llm},
    prepare_data=lambda run, example: {
        "prediction": run.outputs["result"],
        "reference": example.outputs["answer"],
        "input": example.inputs["question"],
    }
)

In [ ]:
# answer와 expected answer 의 similarity 반환해서 평가
embedding_evaluator = LangChainStringEvaluator(
    "embedding_distance",
    config={
        "embeddings": embeddings,
        "distance_metric": "cosine",
    },
)

In [ ]:
experiment_results = evaluate(
    lambda inputs: {"result": chain.invoke(inputs["question"])},
    data="AGENT_DATASET",
    evaluators=[qa_evalulator, conciseness_evalulator, relevance_evalulator, correctness_evalulator, embedding_evaluator],
    experiment_prefix="RAG_EVAL",
)